modLoader="javafml"
loaderVersion="[43,)" #mandatory
license="CC BY-NC-SA 4.0"
[[mods]] #mandatory
modId="exnihiloabnormals" #mandatory
version="0.1.0" #mandatory ${file.jarVersion}
displayName="Ex Nihilo: Sequentia - Abnormals Addon" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="exnihiloabnormals.png" #optional
credits="Ex Nihilo: Sequentia is a mod by NovaMachina" #optional
authors="keriefie" #optional
description='''
Abnormals addon for Ex Nihilo: Sequentia.
'''
[[dependencies.exnihiloabnormals]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.exnihiloabnormals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.exnihiloabnormals]]
    modId="exnihilosequentia"
    mandatory=true
    versionRange="[4.2.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.exnihiloabnormals]]
    modId="jei"
    mandatory=false
    versionRange="[11.6.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.exnihiloabnormals]]
    modId="upgrade_aquatic"
    mandatory=false
    versionRange="[5.0.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.exnihiloabnormals]]
    modId="autumnity"
    mandatory=false
    versionRange="[4.0.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.exnihiloabnormals]]
    modId="environmental"
    mandatory=false
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.exnihiloabnormals]]
    modId="berry_good"
    mandatory=false
    versionRange="[6.0.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.exnihiloabnormals]]
    modId="neapolitan"
    mandatory=false
    versionRange="[4.0.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.exnihiloabnormals]]
    modId="atmospheric"
    mandatory=false
    versionRange="[5.0.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.exnihiloabnormals]]
    modId="caverns_and_chasms"
    mandatory=false
    versionRange="[1.0.0-beta1,1.0.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.exnihiloabnormals]]
    modId="endergetic"
    mandatory=false
    versionRange="[4.0.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.exnihiloabnormals]]
    modId="berry_good"
    mandatory=false
    versionRange="[6.0.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.exnihiloabnormals]]
    modId="clayworks"
    mandatory=false
    versionRange="[2.0.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.exnihiloabnormals]]
    modId="woodworks"
    mandatory=false
    versionRange="[2.2.0,)"
    ordering="AFTER"
    side="BOTH"
